server:
  port: 8899

amireux:
  name: Amireux
  version: 1.0.0
  security:
    tokenExpireTime: 168
    secretExpireTime: 8760
    whiteList:
      - /api/v1/auth/sign_in
      - /api/v1/auth/sign_up

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
