server:
  port: 8899

amireux:
  name: Amireux
  version: 1.0.0
  security:
    tokenExpireTime: 168
    secretExpireTime: 8760
    secretDynamicEnable: false
    secretKey: 123456
    whiteList:
      - /api/v1/auth/sign_in
      - /api/v1/auth/sign_out
      - /actuator
      - /favicon.ico

spring:
  profiles:
    active: dev
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
